package it.gov.pagopa.wispconverter.service.model.re;

public enum EntityStatusEnum {

    RPT_TROVATA,
    DATI_RPT_ESTRATTI,
    PD_ESISTENTE_IN_GPD_NON_VALIDA,
    PD_ESISTENTE_IN_GPD_AGGIORNATA,
    PD_CREATA,
    RPT_CACHE_PER_DECOUPLER_GENERATA,
    REDIRECT_DA_CHECKOUT_OK,
    RT_GENERATA,
    RT_NEGATIVA_NON_GENERABILE,
    RT_INVIATA_OK,
    RT_INVIATA_KO
}
