package it.gov.pagopa.wispconverter.service.model.re;

import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import io.swagger.v3.oas.annotations.media.Schema;
import it.gov.pagopa.wispconverter.repository.model.enumz.EventCategoryEnum;
import lombok.*;

import java.time.Instant;

@Data
@EqualsAndHashCode
@AllArgsConstructor
@NoArgsConstructor
@Builder
@JsonPropertyOrder()
public class ReEventDto {

    private String id;

    @Schema(title = "BOTH", description = "The identifier associated to a request identifier")
    private String operationId;

    @Schema(title = "BOTH", description = "The time on which the event is inserted in RE storage")
    private Instant insertedTimestamp;

    @Schema(title = "BOTH", description = "The category on which the event can be grouped.<br>In NDP it is mapped with field 'categoriaEvento'.")
    private EventCategoryEnum eventCategory;

    @Schema(title = "BOTH", description = "The outcome of the operation described by the event.<br>In NDP it is mapped with field 'esito'.")
    private String outcome;

    @Schema(title = "BOTH", description = "The HTTP method of the endpoint related to the event.<br>This field is set only if the events that describe an HTTP communication with an external service.")
    private String httpMethod;

    @Schema(title = "BOTH", description = "The URI related to the called endpoint.<br>This field is set only if the events that describe an HTTP communication with an external service.")
    private String httpUri;

    @Schema(title = "BOTH", description = "The list of HTTP headers extracted from the request analyzed by the event.<br>This field is set only if the events that describe an HTTP communication with an external service.")
    private String requestHeaders;

    @Schema(title = "BOTH", description = "The list of HTTP headers extracted from the response extracted by the event.<br>This field is set only if the events that describe an HTTP communication with an external service.")
    private String responseHeaders;

    @Schema(title = "BOTH", description = "The status code extracted from the called endpoint.<br>This field is set only if the events that describe an HTTP communication with an external service.")
    private Integer httpStatusCode;

    @Schema(title = "INTERFACE", description = "The duration time of the invocation of the endpoint related to the event.<br>This field is set only if the events that describe an HTTP communication with an external service.")
    private Long executionTimeMs;

    @Schema(title = "BOTH", description = "The payload of the request analyzed by the event.<br>This value is zipped using GZip compression algorithm.")
    private String requestPayload;

    @Schema(title = "BOTH", description = "The payload of the response extracted by the event.<br>This value is zipped using GZip compression algorithm.")
    private String responsePayload;

    @Schema(title = "BOTH", description = "The descriptive label associated to the endpoint called by user and related to the whole process.")
    private String businessProcess;

    @Schema(title = "INTERFACE", description = "The error detail message extracted from the computation that refers to the error occurred during computation.<br>This is set only in the events that describe the response in output to user if there is an error.")
    private String operationErrorDetail;

    @Schema(title = "INTERFACE", description = "The error code extracted from the computation that refers to the error occurred during computation.<br>This is set only in the events that describe the response in output to user if there is an error.")
    private String operationErrorCode;

    @Schema(title = "INTERNAL", description = "The session identifier generated by WISP SOAP Converter and used in the request.")
    private String sessionId;

    @Schema(title = "INTERNAL", description = "The cart identifier used in the request.")
    private String cartId;

    @Schema(title = "INTERNAL", description = "The 'identificativo univoco pagamento' used in the request.")
    private String iuv;

    @Schema(title = "INTERNAL", description = "The notice number (aka NAV code) used in the request.")
    private String noticeNumber;

    @Schema(title = "INTERNAL", description = "The creditor institution identifier used in the request.")
    private String domainId;

    @Schema(title = "INTERNAL", description = "The 'codice contesto pagamento' used in the request.")
    private String ccp;

    @Schema(title = "INTERNAL", description = "The payment service provider used in the request.")
    private String psp;

    @Schema(title = "INTERNAL", description = "The station used in the request.")
    private String station;

    @Schema(title = "INTERNAL", description = "The channel used in the request.")
    private String channel;

    @Schema(title = "INTERNAL", description = "The state of the internal step executed.")
    private String status;

    @Schema(title = "INTERNAL", description = "The other information that can be inserted for the tracing.")
    private String info;

    @Schema(title = "INTERNAL", description = "The payment token.")
    private String paymentToken;
}
