microservice-chart: &microservice-chart
  namespace: "nodo"
  nameOverride: ""
  fullnameOverride: ""
  image:
    repository: ghcr.io/pagopa/pagopa-wisp-converter
    tag: "1.0.6-4-release-v1.0.7"
    pullPolicy: Always
  livenessProbe:
    httpGet:
      path: /actuator/health/liveness
      port: 8080
    initialDelaySeconds: 90
    failureThreshold: 6
    periodSeconds: 10
  readinessProbe:
    httpGet:
      path: /actuator/health/readiness
      port: 8080
    initialDelaySeconds: 90
    failureThreshold: 6
    periodSeconds: 10
  deployment:
    create: true
  service:
    create: true
    type: ClusterIP
    ports:
      - 8080
  ingress: &ingress
    create: true
    host: "weuuat.nodo.internal.uat.platform.pagopa.it"
    path: /pagopa-wisp-converter(/|$)(.*)
    servicePort: 8080
  serviceAccount:
    create: false
    annotations: {}
    name: ""
  podAnnotations: {}
  podSecurityContext:
    seccompProfile:
      type: RuntimeDefault
  securityContext:
    allowPrivilegeEscalation: false
  resources: &resources
    requests:
      memory: "512Mi"
      cpu: "0.25"
    limits:
      memory: "768Mi"
      cpu: "0.50"
  autoscaling: &autoscaling
    enable: true
    minReplica: 1
    maxReplica: 1
    pollingInterval: 10 # seconds
    cooldownPeriod: 50 # seconds
    triggers:
      - type: cpu
        metadata:
          # Required
          type: Utilization # Allowed types are 'Utilization' or 'AverageValue'
          value: "75"
  envConfig: &envConfig
    WEBSITE_SITE_NAME: 'pagopawispconverter' # required to show cloud role name in application insights
    ENV: 'aks-uat'
    APP_LOGGING_LEVEL: 'INFO'
    APP_LOGGING_TRACING_LEVEL: 'ERROR'
    DEFAULT_LOGGING_LEVEL: 'INFO'
    CORS_CONFIGURATION: '{"origins": ["*"], "methods": ["*"]}'
    OTEL_SERVICE_NAME: "pagopa-wisp-converter"
    OTEL_RESOURCE_ATTRIBUTES: "service.environment=uat"
    OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector.elastic-system.svc:4317"
    OTEL_TRACES_EXPORTER: otlp
    OTEL_METRICS_EXPORTER: otlp
    OTEL_LOGS_EXPORTER: none
    OTEL_TRACES_SAMPLER: "always_on"
    REDIS_PORT: "6380"
    COSMOS_URI: "https://pagopa-u-weu-nodo-wispconv-cosmos-account.documents.azure.com:443/"
    COSMOS_READ_REGION: "West Europe"
    COSMOS_CONSISTENCY_LEVEL: "BOUNDED_STALENESS"
    PAAINVIART_SERVICE_BUS_NAME: "nodo_wisp_paainviart_queue"
    RECEIPT_TIMER_QUEUE_NAME: "nodo_wisp_payment_timeout_queue"
    RECEIPT_TIMER_DELTA_ACTIVATE_EXPTIME_MS: '60000'
    ECOMMERCE_HANG_TIMER_QUEUE_NAME: "nodo_wisp_ecommerce_hang_timeout_queue"
    ECOMMERCE_HANG_TIMEOUT: '600'
    APIM_PATH: 'api.uat.platform.pagopa.it'
    CACHED_REQUESTID_MAPPING_TTL_MINUTES: "1440"
    CACHE_REFRESH_CRON: "0 */60 * * * *"
    CLIENT_GPD_READ_TIMEOUT: '5000'
    CLIENT_IUVGENERATOR_READ_TIMEOUT: '5000'
    CLIENT_CHECKOUT_READ_TIMEOUT: '5000'
    CLIENT_DECOUPLERCACHING_READ_TIMEOUT: '5000'
    CLIENT_CACHE_READ_TIMEOUT: '5000'
    CLIENT_GPD_HOST: 'https://api.uat.platform.pagopa.it/gpd/api/v2'
    CLIENT_IUVGENERATOR_HOST: 'https://api.uat.platform.pagopa.it/shared/pagopa-iuvgenerator/v1'
    CLIENT_CHECKOUT_HOST: 'https://api.uat.platform.pagopa.it/checkout/carts-auth/v1'
    CLIENT_DECOUPLERCACHING_HOST: 'https://api.uat.platform.pagopa.it/wisp-converter/caching/api/v1'
    CLIENT_CACHE_HOST: 'https://api.uat.platform.pagopa.it/api-config-cache/p/v1'
    STATION_IN_GPD_PARTIAL_PATH: 'gpd-payments/api/v1'
    RT_SEND_MAX_RETRIES: '5'
    RT_SEND_SCHEDULING_TIME_IN_MINUTES: '60'
    RT_SEND_NO_DEAD_LETTER_ON_STATES: 'PAA_ID_DOMINIO_ERRATO,PAA_ID_INTERMEDIARIO_ERRATO,PAA_STAZIONE_INT_ERRATA,PAA_PAGAMENTO_SCONOSCIUTO,PAA_PAGAMENTO_DUPLICATO,PAA_PAGAMENTO_IN_CORSO,PAA_PAGAMENTO_ANNULLATO,PAA_PAGAMENTO_SCADUTO,PAA_SYSTEM_ERROR'
    RPT_TIMER_QUEUE_NAME: "nodo_wisp_rpt_timeout_queue"
    CRON_JOB_SCHEDULE_RECOVERY_ENABLED: 'false'
    CRON_JOB_SCHEDULE_RECOVERY_RECEIPT_KO_ENABLED: '0 0 * * * *' # top of every hour of every day
    CRON_JOB_SCHEDULE_RECOVERY_FROM_HOURS_AGO: '2' # from 2 hours ago
    CRON_JOB_SCHEDULE_RECOVERY_UNTIL_HOURS_AGO: '1' # until 1 hours ago
    RPT_TIMEOUT: '300' # 5 minutes
    RE_TRACING_INTERFACE_IUVGENERATOR_ENABLED: 'true'
    RE_TRACING_INTERFACE_PAYMENTPOSITIONANALYSIS_ENABLED: 'true'
    RE_TRACING_INTERFACE_DECOUPLERCACHING_ENABLED: 'true'
    RE_TRACING_INTERFACE_CHECKOUTINTERACTION_ENABLED: 'true'
    RE_TRACING_INTERNAL_RPTRETRIEVING_ENABLED: 'true'
    RE_TRACING_INTERNAL_RTRETRIEVING_ENABLED: 'true'
    RE_TRACING_INTERNAL_RPTEXTRACTION_ENABLED: 'true'
    RE_TRACING_INTERNA_PAYMENTPOSITIONANALYSIS_ENABLED: 'true'
    RE_TRACING_INTERNAL_DECOUPLERCACHING_ENABLED: 'true'
    RE_TRACING_INTERNAL_CHECKOUTINTERACTION_ENABLED: 'true'
    SPRING_PROFILES_ACTIVE: "default,jsonLog"
  secretProvider:
    create: true
    envSecrets: &envSecret
      # required
      APPLICATIONINSIGHTS_CONNECTION_STRING: 'azure-insight-connection-string'
      SERVICE_BUS_PAYMENT_TIMEOUT_QUEUE_CONNECTION_STRING: 'wisp-payment-timeout-queue-connection-string'
      SERVICE_BUS_PAAINVIART_QUEUE_CONNECTION_STRING: 'wisp-paainviart-queue-connection-string'
      ECOMMERCE_HANG_TIMER_QUEUE_CONNECTION_STRING: 'ecommerce-hang-timer-queue-connection-string'
      RPT_TIMER_QUEUE_CONNECTION_STRING: 'wisp-rpt-timeout-queue-connection-string'
      OTEL_EXPORTER_OTLP_HEADERS: elastic-apm-secret-token
      REDIS_PASSWORD: 'redis-primary-key'
      REDIS_HOST: 'redis-hostname'
      COSMOS_KEY: 'cosmosdb-wisp-converter-account-key'
      CLIENT_GPD_SUBKEY: 'gpd-pagopa-v1-subscription-key'
      CLIENT_IUVGENERATOR_SUBKEY: 'iuv-generator-subscription-key'
      CLIENT_DECOUPLERCACHING_SUBKEY: 'wisp-converter-caching-subscription-key'
      CLIENT_CACHE_SUBKEY: 'api-config-cache-subscription-key-string'
      CLIENT_CHECKOUT_SUBKEY: 'checkout-subscription-key-string'
      FORWARDER_SUBKEY: 'node-forwarder-subscription-key-string'
    keyvault:
      name: "pagopa-u-nodo-kv"
      tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"
  tmpVolumeMount:
    create: true
  nodeSelector: {}
  tolerations: []
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node_type
                operator: In
                values:
                  - user
  canaryDelivery:
    create: false
    ingress:
      create: true
      canary:
        type: header
        headerName: X-Canary
        headerValue: canary
        weightPercent: 0
    service:
      create: true
    deployment:
      create: true
      image:
        repository: ghcr.io/pagopa/pagopa-wisp-converter
        tag: "0.0.0"
        pullPolicy: Always
      envConfig: {}
      envSecret: {}
# 1 - wisp converter service
app:
  !!merge <<: *microservice-chart
  ingress:
    !!merge <<: *ingress
  resources:
    !!merge <<: *resources
  envConfig:
    !!merge <<: *envConfig
  envSecret:
    !!merge <<: *envSecret
# 2 - wisp converter cron
cron:
  !!merge <<: *microservice-chart
  ingress:
    !!merge <<: *ingress
    path: /pagopa-wisp-converter-notused/(.*)
  resources:
    !!merge <<: *resources
    requests:
      memory: "256Mi"
      cpu: "0.15"
    limits:
      memory: "768Mi"
      cpu: "0.25"
  autoscaling:
    !!merge <<: *autoscaling
    enable: false
    minReplica: 1
    maxReplica: 1
  envConfig:
    !!merge <<: *envConfig
    CRON_JOB_SCHEDULE_RECOVERY_ENABLED: 'true'
    DISABLE_SERVICE_BUS_RECEIVER: 'true'
  envSecret:
    !!merge <<: *envSecret
