package it.gov.pagopa.wispconverter.repository.model.enumz;

public enum InternalStepStatus {

    FOUND_RPT_IN_STORAGE,
    EXTRACTED_DATA_FROM_RPT,
    CREATED_NEW_PAYMENT_POSITION_IN_GPD,
    GENERATED_NAV_FOR_NEW_PAYMENT_POSITION,
    UPDATED_EXISTING_PAYMENT_POSITION_IN_GPD,
    FOUND_INVALID_PAYMENT_POSITION_IN_GPD,
    GENERATED_CACHE_ABOUT_RPT_FOR_DECOUPLER,
    GENERATED_CACHE_ABOUT_RPT_FOR_RT_GENERATION,
    SAVED_RPT_IN_CART_RECEIVED_REDIRECT_URL_FROM_CHECKOUT,
    GENERATED_NEW_RT,
    NEGATIVE_RT_NOT_GENERABLE,
    NEGATIVE_RT_GENERATION_SKIPPED,
    NEGATIVE_RT_GENERATION_SUCCESS,
    RT_SEND_SUCCESS,
    RT_SEND_FAILURE
}
