package it.gov.pagopa.wispconverter.repository.model.enumz;

public enum InternalStepStatus {

    FOUND_RPT_IN_STORAGE,
    EXTRACTED_DATA_FROM_RPT,
    CREATED_NEW_PAYMENT_POSITION_IN_GPD,
    UPDATED_EXISTING_PAYMENT_POSITION_IN_GPD,
    FOUND_INVALID_PAYMENT_POSITION_IN_GPD,
    GENERATED_CACHE_FOR_DECOUPLER_ABOUT_RPT,
    RECEIVED_REDIRECT_URL_FROM_CHECKOUT,
    GENERATED_NEW_RT,
    NEGATIVE_RT_NOT_GENERABLE,
    NEGATIVE_RT_GENERATION_SKIPPED,
    RT_SEND_SUCCESS,
    RT_SEND_FAILURE
}
